"""
Advisor database models
"""
import uuid
from datetime import datetime
from sqlalchemy import (
    Column, String, Float, Integer, DateTime, Text, Boolean,
    ForeignKey, JSON, Enum as SQLEnum
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import enum

from .base import Base


class RecommendationType(enum.Enum):
    """Types of recommendations"""
    IRRIGATION = "irrigation"
    FERTILIZATION = "fertilization"
    PEST_CONTROL = "pest_control"
    DISEASE_TREATMENT = "disease_treatment"
    HARVEST = "harvest"
    SOIL_MANAGEMENT = "soil_management"
    GENERAL = "general"


class AlertSeverity(enum.Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertStatus(enum.Enum):
    """Alert status"""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class ActionStatus(enum.Enum):
    """Action log status"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


class AdvisorSession(Base):
    """
    Stores advisor analysis sessions
    Each session represents one analysis request for a field
    """
    __tablename__ = "advisor_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    field_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    tenant_id = Column(UUID(as_uuid=True), nullable=True, index=True)

    # Analysis context
    analysis_date = Column(DateTime, default=datetime.utcnow)
    context_data = Column(JSON, nullable=True)  # Aggregated context snapshot

    # NDVI Summary
    ndvi_mean = Column(Float, nullable=True)
    ndvi_min = Column(Float, nullable=True)
    ndvi_max = Column(Float, nullable=True)
    ndvi_trend = Column(String(50), nullable=True)  # improving, declining, stable

    # Weather Summary
    weather_summary = Column(JSON, nullable=True)

    # Overall Assessment
    health_score = Column(Float, nullable=True)  # 0-100
    risk_level = Column(String(50), nullable=True)  # low, medium, high, critical

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    recommendations = relationship("Recommendation", back_populates="session")
    alerts = relationship("Alert", back_populates="session")

    def __repr__(self):
        return f"<AdvisorSession {self.id} - Field {self.field_id}>"


class Recommendation(Base):
    """
    Stores recommendations generated by the advisor
    """
    __tablename__ = "recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("advisor_sessions.id"), nullable=False)
    field_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Recommendation details
    type = Column(SQLEnum(RecommendationType), nullable=False)
    title = Column(String(255), nullable=False)
    title_ar = Column(String(255), nullable=True)  # Arabic title
    description = Column(Text, nullable=False)
    description_ar = Column(Text, nullable=True)  # Arabic description

    # Priority and timing
    priority = Column(Integer, default=5)  # 1-10, 10 being highest
    urgency = Column(String(50), default="normal")  # immediate, urgent, normal, low
    recommended_date = Column(DateTime, nullable=True)
    deadline = Column(DateTime, nullable=True)

    # Technical details
    parameters = Column(JSON, nullable=True)  # e.g., {"water_amount": "20mm", "frequency": "daily"}
    affected_zones = Column(JSON, nullable=True)  # List of zone IDs

    # Confidence and source
    confidence_score = Column(Float, default=0.8)  # 0-1
    rule_source = Column(String(100), nullable=True)  # Which rule generated this
    ml_model_version = Column(String(50), nullable=True)

    # Status tracking
    is_active = Column(Boolean, default=True)
    is_accepted = Column(Boolean, nullable=True)
    user_feedback = Column(Text, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)

    # Relationships
    session = relationship("AdvisorSession", back_populates="recommendations")
    action_logs = relationship("ActionLog", back_populates="recommendation")

    def __repr__(self):
        return f"<Recommendation {self.id} - {self.type.value}>"


class Alert(Base):
    """
    Stores alerts generated by the advisor
    """
    __tablename__ = "alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("advisor_sessions.id"), nullable=True)
    field_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    tenant_id = Column(UUID(as_uuid=True), nullable=True, index=True)

    # Alert details
    severity = Column(SQLEnum(AlertSeverity), default=AlertSeverity.WARNING)
    status = Column(SQLEnum(AlertStatus), default=AlertStatus.ACTIVE)

    title = Column(String(255), nullable=False)
    title_ar = Column(String(255), nullable=True)
    message = Column(Text, nullable=False)
    message_ar = Column(Text, nullable=True)

    # Alert type and source
    alert_type = Column(String(100), nullable=False)  # ndvi_drop, weather_warning, etc.
    source = Column(String(100), nullable=True)  # rules_engine, ml_model, external

    # Context
    context_data = Column(JSON, nullable=True)
    affected_zones = Column(JSON, nullable=True)

    # Thresholds
    threshold_value = Column(Float, nullable=True)
    actual_value = Column(Float, nullable=True)

    # Status tracking
    acknowledged_at = Column(DateTime, nullable=True)
    acknowledged_by = Column(UUID(as_uuid=True), nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(UUID(as_uuid=True), nullable=True)
    resolution_notes = Column(Text, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    session = relationship("AdvisorSession", back_populates="alerts")

    def __repr__(self):
        return f"<Alert {self.id} - {self.severity.value}>"


class ActionLog(Base):
    """
    Tracks actions taken based on recommendations
    """
    __tablename__ = "action_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    recommendation_id = Column(UUID(as_uuid=True), ForeignKey("recommendations.id"), nullable=False)
    field_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Action details
    status = Column(SQLEnum(ActionStatus), default=ActionStatus.PENDING)
    action_type = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)

    # Execution details
    scheduled_date = Column(DateTime, nullable=True)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Performer
    performed_by = Column(UUID(as_uuid=True), nullable=True)
    performer_notes = Column(Text, nullable=True)

    # Results
    outcome = Column(String(100), nullable=True)  # success, partial, failed
    outcome_notes = Column(Text, nullable=True)
    measurements = Column(JSON, nullable=True)  # e.g., {"water_applied": "18mm"}

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    recommendation = relationship("Recommendation", back_populates="action_logs")

    def __repr__(self):
        return f"<ActionLog {self.id} - {self.status.value}>"
